PREFIX mluo: <http://example.org/mluo/ontology#>
PREFIX mluo_th: <http://example.org/mluo/thesaurus#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dct: <http://purl.org/dc/terms/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX dcat: <http://www.w3.org/ns/dcat#> 
PREFIX bibo: <http://purl.org/ontology/bibo/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

## The query is filled up upon user interaction with the filters
## The patterns are set on config.json according to the selected filters

SELECT DISTINCT ?p ?author ?label ?date ?type ?url WHERE {

    # $datasetPattern
    
    # $valuesPattern
    # $linkPattern
    # $sourcePattern
    # $targetPattern
    # $themePattern

    # $filterExists
    { SELECT ?dataset (group_concat(distinct ?n ;  separator = '--') as ?author) WHERE {
        # $nodesPattern
    } GROUP BY ?dataset }

    # $filtersPattern
    # $bindingPattern

       
} 
