ARCHITECTURE_CANONICAL = {
 "1x1-convolution": "1X1Convolution",
  "albert": "Albert",
  "amoebanet-a-n18-f448": "AmoebanetAN18F448",
  "anti-alias-downsampling": "AntiAliasDownsampling",
  "attention-dropout": "AttentionDropout",
  "auxiliary-classifier": "AuxiliaryClassifier",
  "average-pooling": "AveragePooling",
  "bart": "Bart",
  "batch-normalization": "BatchNormalization",
  "bert": "Bert",
  "big-transfer": "BigTransfer",
  "bigan": "Bigan",
  "bigbigan": "Bigbigan",
  "biggan": "Biggan",
  "biggan-deep": "BigganDeep",
  "bit": "Bit",
  "blur-pooling": "BlurPooling",
  "bottleneck-residual-block": "BottleneckResidualBlock",
  "cait": "Cait",
  "centernet": "Centernet",
  "condconv": "Condconv",
  "conformer": "Conformer",
  "convmixer": "Convmixer",
  "convnext": "Convnext",
  "convolution": "Convolution",
  "cspdarknet": "Cspdarknet",
  "dan": "Dan",
  "deberta-v3": "DebertaV3",
  "deeplab-mobilenetv2-ade20k-train": "DeeplabMobilenetv2Ade20KTrain",
  "deeplab-mobilenetv2-coco-voc-trainval": "DeeplabMobilenetv2CocoVocTrainval",
  "deeplab-mobilenetv2-dm05-coco-voc-trainval": "DeeplabMobilenetv2Dm05CocoVocTrainval",
  "deeplab-mobilenetv3-large-cityscapes-trainfine": "DeeplabMobilenetv3LargeCityscapesTrainfine",
  "deeplab-xception65-ade20k-train": "DeeplabXception65Ade20KTrain",
  "deeplab-xception65-cityscapes-trainfine": "DeeplabXception65CityscapesTrainfine",
  "deeplab-xception65-coco-voc-trainaug": "DeeplabXception65CocoVocTrainaug",
  "deeplabv3plus": "Deeplabv3Plus",
  "deit": "Deit",
  "delf": "Delf",
  "dense-block": "DenseBlock",
  "dense-connections": "DenseConnections",
  "densenet": "Densenet",
  "depthwise-separable-convolution": "DepthwiseSeparableConvolution",
  "distilbert": "Distilbert",
  "dla-bottleneck-residual-block": "DlaBottleneckResidualBlock",
  "dla-residual-block": "DlaResidualBlock",
  "dpn-block": "DpnBlock",
  "dropout": "Dropout",
  "efficient-channel-attention": "EfficientChannelAttention",
  "efficientdet": "Efficientdet",
  "efficientnet": "Efficientnet",
  "efficientnet-b0": "EfficientnetB0",
  "efficientnet-b1": "EfficientnetB1",
  "efficientnet-b2": "EfficientnetB2",
  "efficientnet-b3": "EfficientnetB3",
  "efficientnet-b4": "EfficientnetB4",
  "efficientnet-b5": "EfficientnetB5",
  "efficientnet-b6": "EfficientnetB6",
  "efficientnet-b7": "EfficientnetB7",
  "efficientnet-v2": "EfficientnetV2",
  "efficientnetv2": "Efficientnetv2",
  "elmo": "Elmo",
  "fastdepth": "Fastdepth",
  "faster-r-cnn": "FasterRCnn",
  "fbnet-block": "FbnetBlock",
  "fcos": "Fcos",
  "fnet": "Fnet",
  "fsaf": "Fsaf",
  "gelu": "Gelu",
  "global-average-pooling": "GlobalAveragePooling",
  "gpt2": "Gpt2",
  "group-normalization": "GroupNormalization",
  "grouped-convolution": "GroupedConvolution",
  "hard-swish": "HardSwish",
  "hrnet-v2-w48": "HrnetV2W48",
  "i3d": "I3D",
  "inception-a": "InceptionA",
  "inception-b": "InceptionB",
  "inception-c": "InceptionC",
  "inception-resnet-v2": "InceptionResnetV2",
  "inception-resnet-v2-a": "InceptionResnetV2A",
  "inception-resnet-v2-b": "InceptionResnetV2B",
  "inception-resnet-v2-c": "InceptionResnetV2C",
  "inception-v1": "InceptionV1",
  "inception-v2": "InceptionV2",
  "inception-v3": "InceptionV3",
  "inception-v3-module": "InceptionV3Module",
  "inception-v4": "InceptionV4",
  "inplace-abn": "InplaceAbn",
  "inverted-residual-block": "InvertedResidualBlock",
  "keywordspottingnet": "Keywordspottingnet",
  "layer-normalization": "LayerNormalization",
  "leaky-relu": "LeakyRelu",
  "mask-r-cnn": "MaskRCnn",
  "max-pooling": "MaxPooling",
  "maxim": "Maxim",
  "midas": "Midas",
  "mish": "Mish",
  "mit": "Mit",
  "mixconv": "Mixconv",
  "mlp-mixer": "MlpMixer",
  "mobilebert": "Mobilebert",
  "mobilebert-edgetpu-small": "MobilebertEdgetpuSmall",
  "mobilebert-uncased-l-24-h-128-b-512-a-4-f-4-opt": "MobilebertUncasedL24H128B512A4F4Opt",
  "mobilenet": "Mobilenet",
  "mobilenet-v1": "MobilenetV1",
  "mobilenet-v2": "MobilenetV2",
  "mobilenet-v3": "MobilenetV3",
  "mobilenetv3": "Mobilenetv3",
  "mobilevit": "Mobilevit",
  "mosaic": "Mosaic",
  "movinet": "Movinet",
  "multi-band-melgan": "MultiBandMelgan",
  "multi-head-attention": "MultiHeadAttention",
  "multiple": "Multiple",
  "nasnet-a-large": "NasnetALarge",
  "nasnet-a-mobile": "NasnetAMobile",
  "nnclr": "Nnclr",
  "nnlm": "Nnlm",
  "one-shot-aggregation": "OneShotAggregation",
  "opt": "Opt",
  "pnasnet-5-large": "Pnasnet5Large",
  "progressive-gan": "ProgressiveGan",
  "reduction-a": "ReductionA",
  "reduction-b": "ReductionB",
  "regnetx": "Regnetx",
  "regnety": "Regnety",
  "relu": "Relu",
  "relu6": "Relu6",
  "reqa": "Reqa",
  "res2net-block": "Res2NetBlock",
  "res2next-block": "Res2NextBlock",
  "residual-block": "ResidualBlock",
  "residual-connection": "ResidualConnection",
  "resnet": "Resnet",
  "resnet-152": "Resnet152",
  "resnet-cifar": "ResnetCifar",
  "resnet-v1-101": "ResnetV1101",
  "resnet-v1-152": "ResnetV1152",
  "resnet-v1-200": "ResnetV1200",
  "resnet-v1-50": "ResnetV150",
  "resnet-v2-101": "ResnetV2101",
  "resnet-v2-152": "ResnetV2152",
  "resnet-v2-50": "ResnetV250",
  "resnet101-v2": "Resnet101V2",
  "resnet101x3-v2": "Resnet101X3V2",
  "resnet152x4-v2": "Resnet152X4V2",
  "resnet19": "Resnet19",
  "resnet50-v2": "Resnet50V2",
  "resnet50x3-v2": "Resnet50X3V2",
  "resnetv1": "Resnetv1",
  "resnetv2": "Resnetv2",
  "resnext-block": "ResnextBlock",
  "retinanet": "Retinanet",
  "roberta": "Roberta",
  "s3d": "S3D",
  "s3d-g": "S3DG",
  "sam": "Sam",
  "scaled-dot-product-attention": "ScaledDotProductAttention",
  "segformer": "Segformer",
  "selecsls-block": "SelecslsBlock",
  "selective-kernel": "SelectiveKernel",
  "silero-stt": "SileroStt",
  "softmax": "Softmax",
  "split-attention": "SplitAttention",
  "squeeze-and-excitation-block": "SqueezeAndExcitationBlock",
  "ssd": "Ssd",
  "ssd-mobilenet-v1": "SsdMobilenetV1",
  "ssd-mobilenet-v2": "SsdMobilenetV2",
  "ssd-mobilenet-v2-fpn": "SsdMobilenetV2Fpn",
  "ssd-spaghettinet-edgetpu-large": "SsdSpaghettinetEdgetpuLarge",
  "swin-transformer": "SwinTransformer",
  "swish": "Swish",
  "swivel": "Swivel",
  "t5": "T5",
  "tacotron-2": "Tacotron2",
  "tanh-activation": "TanhActivation",
  "tnt": "Tnt",
  "transformer": "Transformer",
  "transformer-in-transformer": "TransformerInTransformer",
  "transformer-xl": "TransformerXl",
  "tridentnet": "Tridentnet",
  "tsm-resnet50": "TsmResnet50",
  "tsm-resnet50x2": "TsmResnet50X2",
  "tvn-1": "Tvn1",
  "tvn-2": "Tvn2",
  "tvn-3": "Tvn3",
  "tvn-mobile-1": "TvnMobile1",
  "ulmfit": "Ulmfit",
  "unet": "Unet",
  "vae": "Vae",
  "vgg-style": "VggStyle",
  "video-swin-transformer": "VideoSwinTransformer",
  "videoflow": "Videoflow",
  "vision-transformer": "VisionTransformer",
  "vit": "Vit",
  "vitdet": "Vitdet",
  "wae": "Wae",
  "wav2vec2": "Wav2Vec2",
  "weight-standardization": "WeightStandardization",
  "whisper": "Whisper",
  "wide-residual-block": "WideResidualBlock",
  "wide-resnet-40-8": "WideResnet408",
  "word2vec-skip-gram": "Word2VecSkipGram",
  "wrn-106": "Wrn106",
  "xcit": "Xcit",
  "xlm-roberta": "XlmRoberta",
  "yolo": "Yolo",
  "yolov5": "Yolov5",
  "yolov8": "Yolov8"
}

MODALITY_KAGGLE_CANONICAL = {
    "audio": "Audio",
    "bigquery": "Bigquery",
    "categorical": "Categorical",
    "graph": "Graph",
    "image": "Image",
    "multimodal data": "MultimodalData",
    "synthetic": "Synthetic",
    "tabular": "Tabular",
    "text": "Text",
    "video data": "VideoData"
}

AUDIENCE_CANONICAL = {
    "advanced": "Advanced",
    "beginner": "Beginner",
    "intermediate": "Intermediate"
}

LIBRARY_KAGGLE_CANONICAL = {
    "caret": "Caret",
    "catboost": "Catboost",
    "corrplot": "Corrplot",
    "cv2": "Cv2",
    "d3js": "D3Js",
    "datetime": "Datetime",
    "doParallel": "DoParallel",
    "dplyr": "Dplyr",
    "forcats": "Forcats",
    "foreach": "Foreach",
    "gc": "Gc",
    "ggplot2": "Ggplot2",
    "ggthemes": "Ggthemes",
    "glob": "Glob",
    "gridExtra": "GridExtra",
    "hugging face": "HuggingFace",
    "IPython": "IPython",
    "json": "Json",
    "jsonlite": "Jsonlite",
    "keras": "Keras",
    "knitr": "Knitr",
    "leaflet": "Leaflet",
    "lightgbm": "Lightgbm",
    "lubridate": "Lubridate",
    "matplotlib": "Matplotlib",
    "nltk": "Nltk",
    "numpy": "Numpy",
    "os": "Os",
    "pandas": "Pandas",
    "pathlib": "Pathlib",
    "PIL": "PIL",
    "plotly": "Plotly",
    "plyr": "Plyr",
    "pytorch": "Pytorch",
    "randomForest": "RandomForest",
    "rapids": "Rapids",
    "RColorBrewer": "RColorBrewer",
    "re": "Re",
    "readr": "Readr",
    "reshape2": "Reshape2",
    "rpart": "Rpart",
    "scipy": "Scipy",
    "seaborn": "Seaborn",
    "sklearn": "Sklearn",
    "spaCy": "SpaCy",
    "stringr": "Stringr",
    "sys": "Sys",
    "tabpfn": "Tabpfn",
    "tensorflow": "Tensorflow",
    "tibble": "Tibble",
    "tidyr": "Tidyr",
    "tidyverse": "Tidyverse",
    "torchvision": "Torchvision",
    "tqdm": "Tqdm",
    "transformers": "Transformers",
    "wandb": "Wandb",
    "xgboost": "Xgboost"
}

SUBJECT_CANONICAL = {
    "arts and entertainment": "ArtsAndEntertainment",
    "art": "Art",
    "celebrities": "Celebrities",
    "comics and animation": "ComicsAndAnimation",
    "anime and manga": "AnimeAndManga",
    "dance": "Dance",
    "literature": "Literature",
    "movies and tv shows": "MoviesAndTvShows",
    "museums": "Museums",
    "music": "Music",
    "philosophy": "Philosophy",
    "culture and humanities": "CultureAndHumanities",
    "games": "Games",
    "board games": "BoardGames",
    "card games": "CardGames",
    "gambling": "Gambling",
    "puzzles": "Puzzles",
    "video games": "VideoGames",
    "simulations": "Simulations",
    "languages": "Languages",
    "popular culture": "PopularCulture",
    "cyber security": "CyberSecurity",
    "earth and nature": "EarthAndNature",
    "animals": "Animals",
    "fish and aquaria": "FishAndAquaria",
    "biology": "Biology",
    "genetics": "Genetics",
    "earth science": "EarthScience",
    "atmospheric science": "AtmosphericScience",
    "geography": "Geography",
    "geology": "Geology",
    "environment": "Environment",
    "agriculture": "Agriculture",
    "cities and urban areas": "CitiesAndUrbanAreas",
    "deserts": "Deserts",
    "forestry": "Forestry",
    "mountains": "Mountains",
    "natural disasters": "NaturalDisasters",
    "pollution": "Pollution",
    "water bodies": "WaterBodies",
    "weather and climate": "WeatherAndClimate",
    "physical science": "PhysicalScience",
    "astronomy": "Astronomy",
    "chemistry": "Chemistry",
    "physics": "Physics",
    "plants": "Plants",
    "health and fitness": "HealthAndFitness",
    "exercise": "Exercise",
    "running": "Running",
    "sports": "Sports",
    "auto racing": "AutoRacing",
    "baseball": "Baseball",
    "basketball": "Basketball",
    "cricket": "Cricket",
    "football": "Football",
    "golf": "Golf",
    "hockey": "Hockey",
    "martial arts": "MartialArts",
    "tennis": "Tennis",
    "volleyball": "Volleyball",
    "water sports": "WaterSports",
    "gymnastics": "Gymnastics",
    "food": "Food",
    "alcohol": "Alcohol",
    "cooking and recipes": "CookingAndRecipes",
    "restaurants": "Restaurants",
    "health": "Health",
    "ears and hearing": "EarsAndHearing",
    "eyes and vision": "EyesAndVision",
    "health conditions": "HealthConditions",
    "cancer": "Cancer",
    "diabetes": "Diabetes",
    "diseases": "Diseases",
    "covid19": "Covid19",
    "heart conditions": "HeartConditions",
    "mental health": "MentalHealth",
    "healthcare": "Healthcare",
    "dentistry": "Dentistry",
    "drugs and medications": "DrugsAndMedications",
    "hospitals and treatment centers": "HospitalsAndTreatmentCenters",
    "medicine": "Medicine",
    "neuroscience": "Neuroscience",
    "nutrition": "Nutrition",
    "public health": "PublicHealth",
    "mathematics": "Mathematics",
    "people and society": "PeopleAndSociety",
    "business": "Business",
    "e-commerce services": "ECommerceServices",
    "finance": "Finance",
    "banking": "Banking",
    "crowdfunding": "Crowdfunding",
    "currencies and foreign exchange": "CurrenciesAndForeignExchange",
    "insurance": "Insurance",
    "investing": "Investing",
    "lending": "Lending",
    "marketing": "Marketing",
    "ratings and reviews": "RatingsAndReviews",
    "real estate": "RealEstate",
    "housing": "Housing",
    "travel": "Travel",
    "hotels and accommodations": "HotelsAndAccommodations",
    "education": "Education",
    "primary and secondary schools": "PrimaryAndSecondarySchools",
    "standardized testing": "StandardizedTesting",
    "universities and colleges": "UniversitiesAndColleges",
    "jobs and career": "JobsAndCareer",
    "employment": "Employment",
    "income": "Income",
    "law": "Law",
    "government": "Government",
    "crime": "Crime",
    "military": "Military",
    "public safety": "PublicSafety",
    "news": "News",
    "people": "People",
    "clothing and accessories": "ClothingAndAccessories",
    "gender": "Gender",
    "holidays and cultural events": "HolidaysAndCulturalEvents",
    "make-up and cosmetics": "MakeUpAndCosmetics",
    "retail and shopping": "RetailAndShopping",
    "religion and belief systems": "ReligionAndBeliefSystems",
    "social issues and advocacy": "SocialIssuesAndAdvocacy",
    "human rights": "HumanRights",
    "ml ethics": "MlEthics",
    "racial equity": "RacialEquity",
    "social science": "SocialScience",
    "demographics": "Demographics",
    "mortality": "Mortality",
    "economics": "Economics",
    "history": "History",
    "international relations": "InternationalRelations",
    "linguistics": "Linguistics",
    "politics": "Politics",
    "psychology": "Psychology",
    "urban planning": "UrbanPlanning",
    "science and technology": "ScienceAndTechnology",
    "biotechnology": "Biotechnology",
    "computer science": "ComputerScience",
    "accelerators": "Accelerators",
    "gpu": "Gpu",
    "tpu": "Tpu",
    "artificial intelligence": "ArtificialIntelligence",
    "programming": "Programming",
    "python": "Python",
    "r": "R",
    "sql": "Sql",
    "software": "Software",
    "electronics": "Electronics",
    "energy": "Energy",
    "electricity": "Electricity",
    "oil and gas": "OilAndGas",
    "renewable energy": "RenewableEnergy",
    "engineering": "Engineering",
    "manufacturing": "Manufacturing",
    "robotics": "Robotics",
    "internet": "Internet",
    "email and messaging": "EmailAndMessaging",
    "mobile and wireless": "MobileAndWireless",
    "online communities": "OnlineCommunities",
    "social networks": "SocialNetworks",
    "search engines": "SearchEngines",
    "websites": "Websites",
    "research": "Research",
    "transportation": "Transportation",
    "automobiles and vehicles": "AutomobilesAndVehicles",
    "aviation": "Aviation",
    "cycling": "Cycling",
    "rail transport": "RailTransport",
    "water transport": "WaterTransport"
}

TASK_KAGGLE_CANONICAL = {
   "aesthetic-quality": "AestheticQuality",
    "audio-classification": "AudioClassification",
    "audio-command-detection": "AudioCommandDetection",
    "audio-event-classification": "AudioEventClassification",
    "audio-synthesis": "AudioSynthesis",
    "audio-to-audio": "AudioToAudio",
    "automatic-speech-recognition": "AutomaticSpeechRecognition",
    "binary-classification": "BinaryClassification",
    "classification": "Classification",
    "clustering": "Clustering",
    "deblurring": "Deblurring",
    "dehazing": "Dehazing",
    "denoising": "Denoising",
    "distance": "Distance",
    "evaluation": "Evaluation",
    "coding": "Coding",
    "factuality-and-grounding": "FactualityAndGrounding",
    "general-knowledge-and-reasoning": "GeneralKnowledgeAndReasoning",
    "math": "Math",
    "multilingual-and-cross-lingual-capabilities": "MultilingualAndCrossLingualCapabilities",
    "feature-extraction": "FeatureExtraction",
    "frame-interpolation": "FrameInterpolation",
    "image-augmentation": "ImageAugmentation",
    "image-classification": "ImageClassification",
    "image-classification-logits": "ImageClassificationLogits",
    "image-depth-estimation": "ImageDepthEstimation",
    "image-extrapolation": "ImageExtrapolation",
    "image-feature-vector": "ImageFeatureVector",
    "image-generator": "ImageGenerator",
    "image-segmentation": "ImageSegmentation",
    "image-style-transfer": "ImageStyleTransfer",
    "image-super-resolution": "ImageSuperResolution",
    "image-text-detection": "ImageTextDetection",
    "image-text-recognition": "ImageTextRecognition",
    "image-to-image": "ImageToImage",
    "image-to-text": "ImageToText",
    "imagenet-2012-classification": "Imagenet2012Classification",
    "linear regression": "LinearRegression",
    "logistic regression": "LogisticRegression",
    "multiclass classification": "MulticlassClassification",
    "multilabel-classification": "MultilabelClassification",
    "multitask-classification": "MultitaskClassification",
    "object-detection": "ObjectDetection",
    "other": "Other",
    "paralinguistic-classification": "ParalinguisticClassification",
    "pitch-extraction": "PitchExtraction",
    "pose-detection": "PoseDetection",
    "question-answering": "QuestionAnswering",
    "regression": "Regression",
    "reinforcement-learning": "ReinforcementLearning",
    "retrieval-question-answering": "RetrievalQuestionAnswering",
    "retrieval/ranking": "RetrievalRanking",
    "segmentation": "Segmentation",
    "sentence-similarity": "SentenceSimilarity",
    "speech-synthesis": "SpeechSynthesis",
    "speech-to-text": "SpeechToText",
    "summarization": "Summarization",
    "tabular-classification": "TabularClassification",
    "text-classification": "TextClassification",
    "text-conversation": "TextConversation",
    "text-fill-mask": "TextFillMask",
    "text-generation": "TextGeneration",
    "text-pre-processing": "TextPreProcessing",
    "text-segmentation": "TextSegmentation",
    "text-sequence-alignment": "TextSequenceAlignment",
    "text-to-image": "TextToImage",
    "text-to-mel": "TextToMel",
    "text-to-speech": "TextToSpeech",
    "text-to-text-generation": "TextToTextGeneration",
    "token-classification": "TokenClassification",
    "translation": "Translation",
    "video-audio-text": "VideoAudioText",
    "video-classification": "VideoClassification",
    "video-generation": "VideoGeneration",
    "video-text": "VideoText",
    "zero-shot-text-classification": "ZeroShotTextClassification"
}

TECHNIQUE_CANONICAL = {
    "adversarial learning": "AdversarialLearning",
    "automl": "Automl",
    "bayesian statistics": "BayesianStatistics",
    "benchmark": "Benchmark",
    "computer vision": "ComputerVision",
    "data analytics": "DataAnalytics",
    "data storytelling": "DataStorytelling",
    "data visualization": "DataVisualization",
    "decision tree": "DecisionTree",
    "deep learning": "DeepLearning",
    "dimensionality reduction": "DimensionalityReduction",
    "ensembling": "Ensembling",
    "exploratory data analysis": "ExploratoryDataAnalysis",
    "feature engineering": "FeatureEngineering",
    "gradient boosting": "GradientBoosting",
    "graph neural network": "GraphNeuralNetwork",
    "k-means": "KMeans",
    "knn": "Knn",
    "model comparison": "ModelComparison",
    "model explainability": "ModelExplainability",
    "naive bayes": "NaiveBayes",
    "neural networks": "NeuralNetworks",
    "cnn": "Cnn",
    "dnn": "Dnn",
    "gan": "Gan",
    "lstm": "Lstm",
    "rnn": "Rnn",
    "optimization": "Optimization",
    "outlier analysis": "OutlierAnalysis",
    "pca": "Pca",
    "random forest": "RandomForest",
    "recommender systems": "RecommenderSystems",
    "sampling": "Sampling",
    "svm": "Svm",
    "time series analysis": "TimeSeriesAnalysis",
    "transfer learning": "TransferLearning"
}

ANALYSIS_CANONICAL = {
    "data cleaning": "DataCleaning",
    "geospatial analysis": "GeospatialAnalysis",
    "nlp": "Nlp",
    "signal processing": "SignalProcessing",
    "statistical analysis": "StatisticalAnalysis",
    "survey analysis": "SurveyAnalysis",
    "text mining": "TextMining"
}