import re
from typing import Any
from .parser_tools import dedupe, hash16, normalize_string

MODALITY_CANONICAL = {
    '3d': '3D',
    'audio': 'Audio',
    'document': 'Document',
    'geospatial': 'Geospatial',
    'image': 'Image',
    'tabular': 'Tabular',
    'text': 'Text',
    'timeseries': 'TimeSeries',
    'time_series': 'TimeSeries',
    'time-series': 'TimeSeries',
    'video': 'Video',
}

FORMAT_CANONICAL = {
    'webdataset': 'WebDataset',
    'imagefolder': 'ImageFolder',
    'audiofolder': 'AudioFolder',
    'agent-traces': 'AgentTraces',
    'arrow': 'Arrow',
    'csv': 'CSV',
    'json': 'JSON',
    'parquet': 'Parquet',
    'optimized-parquet': 'OptimizedParquet',
    'text': 'Text',
}

SIZE_CATEGORY_CANONICAL = {
    'n<1k': '1',
    '<1k': '1',
    'lt-1k': '1',
    'size-lt-1k': '1',
    '1k<n<10k': '1k',
    'size-1k-to-10k': '1k',
    '10k<n<100k': '10k',
    'size-10k-to-100k': '10k',
    '100k<n<1m': '100k',
    'size-100k-to-1m': '100k',
    '1m<n<10m': '1m',
    'size-1m-to-10m': '1m',
    '10m<n<100m': '10m',
    'size-10m-to-100m': '10m',
    '100m<n<1b': '100m',
    'size-100m-to-1b': '100m',
    '1b<n<10b': '1b',
    'size-1b-to-10b': '1b',
    '10b<n<100b': '10b',
    'size-10b-to-100b': '10b',
    '100b<n<1t': '100b',
    'size-100b-to-1t': '100b',
    'n>1t': '1t',
    '>1t': '1t',
    'gt-1t': '1t',
    'size-gt-1t': '1t',
}

DATASET_LIBRARY_CANONICAL = {
    'datadesigner': 'DataDesigner',
    'lance': 'Lance',
    'datasets': 'Datasets',
    'webdataset': 'WebDatasetFormat',
    'polars': 'Polars',
    'dask': 'Dask',
    'pandas': 'Pandas',
    'fiftyone': 'FiftyOne',
    'distilabel': 'Distilabel',
    'mlcroissant': 'MLCroissant',
    'argilla': 'Argilla',
}

MODEL_LIBRARY_CANONICAL = {
    'pytorch': 'Pytorch',
    'sklearn': 'Sklearn',
    'transformers.js': 'TransformersJS',
    'transformers': 'Transformers',
    'allennlp': 'AllenNLP',
    'stanza': 'Stanza',
    'PaddleOCR': 'PaddleOCR',
    'adapter-transformers': 'AdapterTransformers',
    'rust': 'Rust',
    'keras-hub': 'KerasHub',
    'sentence-transformers': 'SentenceTransformers',
    'speechbrain': 'Speechbrain',
    'tflite': 'LiteRT',
    'espnet': 'Espnet',
    'pyannote-audio': 'PyannoteAudio',
    'open-clip': 'OpenClip',
    'peft': 'Peft',
    'fasttext': 'Fasttext',
    'tensorboard': 'Tensorboard',
    'keras': 'Keras',
    'stable-baselines3': 'StableBaselines3',
    'nemo': 'Nemo',
    'asteroid': 'Asteroid',
    'optimum_graphcore': 'OptimumGraphcore',
    'tf-keras': 'TFKeras',
    'span-marker': 'SpanMarker',
    'paddlenlp': 'PaddleNLP',
    'joblib': 'Joblib',
    'optimum_habana': 'OptimumHabana',
    'univa': 'Univa',
    'dduf': 'DDUF',
    'openvino': 'OpenVINO',
    'gguf': 'GGUF',
    'flair': 'Flair',
    'coreml': 'CoreML',
    'setfit': 'SetFit',
    'onnx': 'ONNX',
    'jax': 'Jax',
    'spacy': 'Spacy',
    'diffusers': 'Diffusers',
    'llamafile': 'LlamaFile',
    'sample-factory': 'SampleFactory',
    'fairseq': 'Fairseq',
    'timm': 'Timm',
    'paddlepaddle': 'PaddlePaddle',
    'ml-agents': 'MLAgents',
    'fastai': 'FastAI',
    'executorch': 'ExecuTorch',
    'tf': 'TF',
    'mlx': 'MLX',
    'unity-sentis': 'UnitySentis',
    'safetensors': 'Safetensors',
    'bertopic': 'BERTopic',
}

TASK_CANONICAL = {
    'document-question-answering': 'DocumentQuestionAnswering',
    'audio-classification': 'AudioClassification',
    'image-to-image': 'ImageToImage',
    'tabular-regression': 'TabularRegression',
    'image-segmentation': 'ImageSegmentation',
    'unconditional-image-generation': 'UnconditionalImageGeneration',
    'image-to-text': 'ImageToText',
    'any-to-any': 'AnyToAny',
    'zero-shot-classification': 'ZeroShotClassification',
    'time-series-forecasting': 'TimeSeriesForecasting',
    'zero-shot-object-detection': 'ZeroShotObjectDetection',
    'robotics': 'Robotics',
    'reinforcement-learning': 'ReinforcementLearning',
    'mask-generation': 'MaskGeneration',
    'feature-extraction': 'FeatureExtraction',
    'text-to-audio': 'TextToAudio',
    'audio-to-audio': 'AudioToAudio',
    'image-to-video': 'ImageToVideo',
    'video-classification': 'VideoClassification',
    'tabular-to-text': 'TabularToText',
    'fill-mask': 'FillMask',
    'object-detection': 'ObjectDetection',
    'zero-shot-image-classification': 'ZeroShotImageClassification',
    'token-classification': 'TokenClassification',
    'image-feature-extraction': 'ImageFeatureExtraction',
    'text-to-video': 'TextToVideo',
    'image-classification': 'ImageClassification',
    'text-generation': 'TextGeneration',
    'tabular-classification': 'TabularClassification',
    'multiple-choice': 'MultipleChoice',
    'image-text-to-text': 'ImageTextToText',
    'visual-question-answering': 'VisualQuestionAnswering',
    'summarization': 'Summarization',
    'image-text-to-image': 'ImageTextToImage',
    'sentence-similarity': 'SentenceSimilarity',
    'text-to-3d': 'TextTo3D',
    'video-text-to-text': 'VideoTextToText',
    'image-to-3d': 'ImageTo3D',
    'visual-document-retrieval': 'VisualDocumentRetrieval',
    'automatic-speech-recognition': 'AutomaticSpeechRecognition',
    'audio-text-to-text': 'AudioTextToText',
    'text-retrieval': 'TextRetrieval',
    'depth-estimation': 'DepthEstimation',
    'table-to-text': 'TableToText',
    'image-text-to-video': 'ImageTextToVideo',
    'table-question-answering': 'TableQuestionAnswering',
    'question-answering': 'QuestionAnswering',
    'graph-ml': 'GraphML',
    'translation': 'Translation',
    'keypoint-detection': 'KeypointDetection',
    'voice-activity-detection': 'VoiceActivityDetection',
    'text-classification': 'TextClassification',
    'text-to-speech': 'TextToSpeech',
    'text-to-image': 'TextToImage',
    'video-to-video': 'VideoToVideo',
    'text-ranking': 'TextRanking',
}

SUBTASK_CANONICAL = {
    'named-entity-recognition': 'NamedEntityRecognition',
    'pose-estimation': 'PoseEstimation',
    'document-question-answering': 'DocumentQuestionAnswering',
    'open-domain-abstractive-qa': 'OpenDomainAbstractiveQA',
    'entity-linking-retrieval': 'EntityLinkingRetrieval',
    'multi-class-image-classification': 'MultiClassImageClassification',
    'explanation-generation': 'ExplanationGeneration',
    'multi-input-text-classification': 'MultiInputTextClassification',
    'keyword-spotting': 'KeywordSpotting',
    'dialogue-generation': 'DialogueGeneration',
    'tabular-multi-label-classification': 'TabularMultiLabelClassification',
    'part-of-speech': 'PartOfSpeech',
    'language-modeling': 'LanguageModeling',
    'multi-label-classification': 'MultiLabelClassification',
    'super-resolution': 'SuperResolution',
    'univariate-time-series-forecasting': 'UnivariateTimeSeriesForecasting',
    'entity-linking-classification': 'EntityLinkingClassification',
    'text-simplification': 'TextSimplification',
    'natural-language-inference': 'NaturalLanguageInference',
    'image-inpainting': 'ImageInpainting',
    'conversational': 'Conversational',
    'text-scoring': 'TextScoring',
    'hate-speech-detection': 'HateSpeechDetection',
    'dialogue-modeling': 'DialogueModeling',
    'speaker-identification': 'SpeakerIdentification',
    'closed-book-qa': 'ClosedBookQA',
    'news-articles-summarization': 'NewsArticlesSummarization',
    'coreference-resolution': 'CoreferenceResolution',
    'news-articles-headline-generation': 'NewsArticlesHeadlineGeneration',
    'document-retrieval': 'DocumentRetrieval',
    'semantic-similarity-scoring': 'SemanticSimilarityScoring',
    'parsing': 'Parsing',
    'lemmatization': 'Lemmatization',
    'multiple-choice-qa': 'MultipleChoiceQA',
    'multi-label-image-classification': 'MultiLabelImageClassification',
    'sentiment-classification': 'SentimentClassification',
    'utterance-retrieval': 'UtteranceRetrieval',
    'panoptic-segmentation': 'PanopticSegmentation',
    'slot-filling': 'SlotFilling',
    'image-captioning': 'ImageCaptioning',
    'audio-language-identification': 'AudioLanguageIdentification',
    'visual-question-answering': 'VisualQuestionAnswering',
    'topic-classification': 'TopicClassification',
    'multivariate-time-series-forecasting': 'MultivariateTimeSeriesForecasting',
    'semantic-similarity-classification': 'SemanticSimilarityClassification',
    'audio-intent-classification': 'AudioIntentClassification',
    'rdf-to-text': 'RDFToText',
    'fact-checking': 'FactChecking',
    'sentiment-scoring': 'SentimentScoring',
    'semantic-segmentation': 'SemanticSegmentation',
    'extractive-qa': 'ExtractiveQA',
    'grasping': 'Grasping',
    'vehicle-detection': 'VehicleDetection',
    'language-identification': 'LanguageIdentification',
    'text2textgeneration': 'Text2TextGeneration',
    'open-domain-qa': 'OpenDomainQA',
    'fact-checking-retrieval': 'FactCheckingRetrieval',
    'image-colorization': 'ImageColorization',
    'open-book-qa': 'OpenBookQA',
    'task-planning': 'TaskPlanning',
    'masked-language-modeling': 'MaskedLanguageModeling',
    'abstractive-qa': 'AbstractiveQA',
    'instance-segmentation': 'InstanceSegmentation',
    'intent-classification': 'IntentClassification',
    'sentiment-analysis': 'SentimentAnalysis',
    'word-sense-disambiguation': 'WordSenseDisambiguation',
    'multi-class-classification': 'MultiClassClassification',
    'acceptability-classification': 'AcceptabilityClassification',
    'tabular-single-column-regression': 'TabularSingleColumnRegression',
    'closed-domain-qa': 'ClosedDomainQA',
    'face-detection': 'FaceDetection',
    'multiple-choice-coreference-resolution': 'MultipleChoiceCoreferenceResolution',
    'audio-emotion-recognition': 'AudioEmotionRecognition',
    'tabular-multi-class-classification': 'TabularMultiClassClassification',
}

MULTILINGUARITY_CANONICAL = {
    "monolingual": "Monolingual",
    "bilingual": "Bilingual",
    "multilingual": "Multilingual",
    "translation": "Translation",
    "translated": "Translation",
}

MODEL_FAMILY_CANONICAL = {
    "afmoe": "AFMoE",
    "albert": "ALBERT",
    "apertus": "Apertus",
    "arcee": "Arcee",
    "bamba": "Bamba",
    "bart": "BART",
    "barthez": "BARThez",
    "bartpho": "BARTpho",
    "bert": "BERT",
    "bert-generation": "BertGeneration",
    "bert-japanese": "BertJapanese",
    "bertweet": "BERTweet",
    "big_bird": "BigBird",
    "bigbird_pegasus": "BigbirdPegasus",
    "biogpt": "BioGPT",
    "bitnet": "BitNet",
    "blenderbot": "Blenderbot",
    "blenderbot-small": "BlenderbotSmall",
    "bloom": "BLOOM",
    "blt": "BLT",
    "byt5": "ByT5",
    "camembert": "CamemBERT",
    "canine": "CANINE",
    "codegen": "CodeGen",
    "code_llama": "CodeLlama",
    "cohere": "Cohere",
    "cohere2": "Cohere2",
    "cohere2_moe": "Cohere2Moe",
    "convbert": "ConvBERT",
    "cpm": "CPM",
    "cpmant": "CPMAnt",
    "ctrl": "CTRL",
    "dbrx": "DBRX",
    "deberta": "DeBERTa",
    "deberta-v2": "DeBERTaV2",
    "deepseek_ocr2": "DeepSeekOCR2",
    "deepseek_v2": "DeepSeekV2",
    "deepseek_v3": "DeepSeekV3",
    "deepseek_v32": "DeepSeekV32",
    "deepseek_v4": "DeepSeekV4",
    "dialogpt": "DialogGPT",
    "diffllama": "DiffLlama",
    "distilbert": "DistilBERT",
    "doge": "Doge",
    "dots1": "Dots1",
    "dpr": "DPR",
    "electra": "ELECTRA",
    "encoder-decoder": "EncoderDecoder",
    "ernie": "ERNIE",
    "ernie4_5": "Ernie45",
    "ernie4_5_moe": "Ernie45Moe",
    "esm": "ESM",
    "eurobert": "EuroBERT",
    "exaone4": "EXAONE4",
    "exaone4_5": "EXAONE45",
    "exaone_moe": "EXAONEMoe",
    "falcon": "Falcon",
    "falcon3": "Falcon3",
    "falcon_h1": "FalconH1",
    "falcon_mamba": "FalconMamba",
    "flan-t5": "FLANT5",
    "flan-ul2": "FLANUL2",
    "flaubert": "FlauBERT",
    "flex_olmo": "FlexOlmo",
    "fnet": "FNet",
    "fsmt": "FSMT",
    "funnel": "Funnel",
    "fuyu": "Fuyu",
    "gemma": "Gemma",
    "gemma2": "Gemma2",
    "glm": "Glm",
    "glm4": "Glm4",
    "glm4_moe": "Glm4Moe",
    "glm4_moe_lite": "Glm4MoeLite",
    "glm_image": "GlmImage",
    "glm_moe_dsa": "GlmMoeDsa",
    "openai-gpt": "GPT",
    "gpt": "GPT",
    "GPT": "GPT",
    "gpt-neo": "GPTNeo",
    "GPT-NEO": "GPTNeo",
    "gpt_neox": "GPTNeox",
    "gpt_neox_japanese": "GPTNeoxJapanese",
    "gptj": "GPTJ",
    "gpt2": "GPT2",
    "gpt_bigcode": "GPTBigCode",
    "gpt_oss": "GPTOss",
    "gpt-sw3": "GPTSw3",
    "granite": "Granite",
    "granitemoe": "GraniteMoe",
    "granitemoehybrid": "GraniteMoeHybrid",
    "granitemoeshared": "GraniteMoeShared",
    "helium": "Helium",
    "herbert": "HerBERT",
    "hrm_text": "HRMText",
    "hunyuan_v1_dense": "HunYuanDenseV1",
    "hunyuan_v1_moe": "HunYuanMoEV1",
    "hunyuan_vl": "HunYuanVL",
    "hyperclovax": "HyperCLOVAX",
    "hy_v3": "HYV3",
    "ibert": "IBERT",
    "jais2": "Jais2",
    "jamba": "Jamba",
    "jetmoe": "JetMoe",
    "jina_embeddings_v3": "JinaEmbeddingsV3",
    "laguna": "Laguna",
    "led": "LED",
    "lfm2": "LFM2",
    "lfm2_moe": "LFM2Moe",
    "llama": "Llama",
    "llama2": "Llama2",
    "llama3": "Llama3",
    "longcat_flash": "LongCatFlash",
    "longformer": "Longformer",
    "longt5": "LongT5",
    "luke": "LUKE",
    "m2m_100": "M2M100",
    "madlad-400": "MADLAD400",
    "mamba": "Mamba",
    "mamba2": "Mamba2",
    "marian": "MarianMT",
    "markuplm": "MarkupLM",
    "mbart": "MBART",
    "megatron-bert": "MegatronBERT",
    "megatron_gpt2": "MegatronGPT2",
    "mellum": "Mellum",
    "mimo_v2_flash": "MiMoV2Flash",
    "minicpm3": "MiniCPM3",
    "minimax": "MiniMax",
    "minimax_m2": "MiniMaxM2",
    "minimax_m3_vl": "MiniMaxM3VL",
    "ministral": "Ministral",
    "ministral3": "Ministral3",
    "mistral": "Mistral",
    "mixtral": "Mixtral",
    "mluke": "MLUKE",
    "mobilebert": "MobileBERT",
    "modernbert": "ModernBERT",
    "modernbert-decoder": "ModernBERTDecoder",
    "modernvbert": "ModernVBert",
    "mpnet": "MPNet",
    "mpt": "MPT",
    "mra": "MRA",
    "mt5": "MT5",
    "mvp": "MVP",
    "myt5": "MyT5",
    "nanochat": "NanoChat",
    "nemotron": "Nemotron",
    "nemotron_h": "NemotronH",
    "nllb": "NLLB",
    "nllb-moe": "NLLBMoe",
    "nomic_bert": "NomicBERT",
    "nystromformer": "Nystromformer",
    "olmo": "OLMo",
    "olmo2": "OLMo2",
    "olmo3": "OLMo3",
    "olmoe": "OLMoE",
    "olmo_hybrid": "OLMoHybrid",
    "openai_privacy_filter": "OpenAIPrivacyFilter",
    "opt": "OPT",
    "pegasus": "Pegasus",
    "pegasus_x": "PegasusX",
    "persimmon": "Persimmon",
    "phi": "Phi",
    "phi3": "Phi3",
    "phimoe": "PhiMoE",
    "phobert": "PhoBERT",
    "plbart": "PLBART",
    "prophetnet": "ProphetNet",
    "qwen2": "Qwen2",
    "qwen2_moe": "Qwen2MoE",
    "qwen3": "Qwen3",
    "qwen3_5": "Qwen35",
    "qwen3_moe": "Qwen3MoE",
    "rag": "RAG",
    "recurrent_gemma": "RecurrentGemma",
    "reformer": "Reformer",
    "rembert": "RemBERT",
    "roberta": "RoBERTa",
    "roberta-prelayernorm": "RoBERTaPrelayernorm",
    "roc_bert": "RoCBert",
    "roformer": "Roformer",
    "rwkv": "RWKV",
    "seed_oss": "SeedOss",
    "smollm3": "SmolLM3",
    "solar_open": "SolarOpen",
    "splinter": "Splinter",
    "squeezebert": "SqueezeBERT",
    "stablelm": "StableLM",
    "starcoder2": "Starcoder2",
    "switch_transformers": "SwitchTransformers",
    "t5": "T5",
    "t5gemma": "T5Gemma",
    "t5gemma2": "T5Gemma2",
    "t5v1": "T5V1",
    "ul2": "UL2",
    "umt5": "UMT5",
    "vaultgemma": "VaultGemma",
    "xmod": "XMOD",
    "xglm": "XGLM",
    "xlm": "XLM",
    "xlm-roberta": "XLMRoBERTa",
    "xlm-roberta-xl": "XLMRoBERTaXL",
    "xlm-v": "XLMV",
    "xlnet": "XLNet",
    "xlstm": "XLSTM",
    "yoso": "YOSO",
    "youtu": "Youtu",
    "zamba": "Zamba",
    "zamba2": "Zamba2",
    "zaya": "ZAYA",
    "aimv2": "AIMv2",
    "beit": "BEiT",
    "bit": "BiT",
    "chmv2": "CHMv2",
    "conditional_detr": "ConditionalDETR",
    "convnext": "ConvNeXT",
    "convnextv2": "ConvNeXtV2",
    "cvt": "CvT",
    "d_fine": "DFINE",
    "dab-detr": "DABDETR",
    "deformable_detr": "DeformableDETR",
    "deimv2": "DEIMv2",
    "deit": "DeiT",
    "depth_anything": "DepthAnything",
    "depth_anything_v2": "DepthAnythingV2",
    "depth_pro": "DepthPro",
    "detr": "DETR",
    "dinat": "DiNAT",
    "dinov2": "DINOv2",
    "dinov2_with_registers": "DINOv2WithRegisters",
    "dinov3": "DINOv3",
    "dit": "DiT",
    "dpt": "DPT",
    "efficientloftr": "EfficientLoFTR",
    "efficientnet": "EfficientNet",
    "eomt": "EoMT",
    "eomt_dinov3": "EoMTDINOv3",
    "focalnet": "FocalNet",
    "glpn": "GLPN",
    "hgnet_v2": "HGNetV2",
    "hiera": "Hiera",
    "ijepa": "IJEPA",
    "imagegpt": "ImageGPT",
    "levit": "LeViT",
    "lightglue": "LightGlue",
    "lw_detr": "LWDETR",
    "mask2former": "Mask2Former",
    "maskformer": "MaskFormer",
    "mlcd": "MLCD",
    "mobilenet_v1": "MobileNetV1",
    "mobilenet_v2": "MobileNetV2",
    "mobilevit": "MobileViT",
    "mobilevitv2": "MobileViTV2",
    "pixio": "Pixio",
    "poolformer": "PoolFormer",
    "prompt_depth_anything": "PromptDepthAnything",
    "pvt": "PVT",
    "pvt_v2": "PVTV2",
    "radio": "RADIO",
    "regnet": "RegNet",
    "resnet": "ResNet",
    "rf_detr": "RFDETR",
    "rt_detr": "RTDETR",
    "rt_detr_v2": "RTDETRV2",
    "sam2": "SAM2",
    "sam3_tracker": "SAM3Tracker",
    "sapiens2": "Sapiens2",
    "segformer": "SegFormer",
    "seggpt": "SegGPT",
    "sam": "SAM",
    "sam_hq": "SAMHQ",
    "superglue": "SuperGlue",
    "superpoint": "SuperPoint",
    "swiftformer": "SwiftFormer",
    "swin": "SwinTransformer",
    "swin_transformer": "SwinTransformer",
    "swinv2": "SwinTransformerV2",
    "swin2sr": "Swin2SR",
    "table-transformer": "TableTransformer",
    "textnet": "Textnet",
    "timm_wrapper": "TimmWrapper",
    "upernet": "UPerNet",
    "uvdoc": "UVDoc",
    "videomt": "VidEoMT",
    "vit": "ViT",
    "vitdet": "ViTDet",
    "vit_mae": "ViTMAE",
    "vitmatte": "ViTMatte",
    "vit_msn": "ViTMSN",
    "vitpose": "ViTPose",
    "yolos": "YOLOS",
    "zoedepth": "ZoeDepth",
    "audio-spectrogram-transformer": "AudioSpectrogramTransformer",
    "bark": "Bark",
    "clap": "CLAP",
    "csm": "CSM",
    "dac": "DAC",
    "dia": "Dia",
    "encodec": "EnCodec",
    "fastspeech2_conformer": "FastSpeech2Conformer",
    "glmasr": "Glmasr",
    "granite_speech": "GraniteSpeech",
    "granite_speech_plus": "GraniteSpeechPlus",
    "higgs_audio_v2": "HiggsAudioV2",
    "higgs_audio_v2_tokenizer": "HiggsAudioV2Tokenizer",
    "hubert": "HuBERT",
    "kyutai_speech_to_text": "KyutaiSpeechToText",
    "lasr": "LASR",
    "mimi": "Mimi",
    "mms": "MMS",
    "moonshine": "Moonshine",
    "moonshine_streaming": "MoonshineStreaming",
    "moshi": "Moshi",
    "musicgen": "MusicGen",
    "musicgen_melody": "MusicGenMelody",
    "nemotron3_5_asr": "Nemotron35ASR",
    "pe_audio": "PEAudio",
    "qwen3_asr": "Qwen3ASR",
    "seamless_m4t": "SeamlessM4T",
    "seamless_m4t_v2": "SeamlessM4TV2",
    "sew": "SEW",
    "sew-d": "SEWD",
    "speech_to_text": "Speech2Text",
    "speecht5": "SpeechT5",
    "unispeech": "UniSpeech",
    "unispeech-sat": "UniSpeechSAT",
    "univnet": "UnivNet",
    "vibevoice_acoustic_tokenizer": "VibeVoiceAcousticTokenizer",
    "vibevoice_asr": "VibeVoiceASR",
    "vits": "VITS",
    "wav2vec2": "Wav2Vec2",
    "wav2vec2-bert": "Wav2Vec2BERT",
    "wav2vec2-conformer": "Wav2Vec2Conformer",
    "wav2vec2_phoneme": "Wav2Vec2Phoneme",
    "wavlm": "WavLM",
    "whisper": "Whisper",
    "xcodec": "XCodec",
    "xcodec2": "XCodec2",
    "xls_r": "XLSR",
    "xlsr_wav2vec2": "XLSRWav2Vec2",
    "pe_video": "PEVideo",
    "sam2_video": "SAM2Video",
    "sam3_tracker_video": "SAM3TrackerVideo",
    "timesformer": "TimeSformer",
    "vjepa2": "VJEPA2",
    "videomae": "VideoMAE",
    "videoprism": "VideoPrism",
    "vivit": "ViViT",
    "align": "ALIGN",
    "altclip": "AltCLIP",
    "aria": "Aria",
    "audioflamingo3": "AudioFlamingo3",
    "aya_vision": "AyaVision",
    "blip": "BLIP",
    "blip-2": "BLIP2",
    "bridgetower": "Bridgetower",
    "bros": "BROS",
    "chameleon": "Chameleon",
    "chinese_clip": "ChineseCLIP",
    "clip": "CLIP",
    "clipseg": "CLIPseg",
    "clvp": "CLVP",
    "cwm": "CWM",
    "cohere2_vision": "Cohere2Vision",
    "colmodernvbert": "ColModernVBert",
    "colpali": "ColPali",
    "colqwen2": "ColQwen2",
    "cosmos3_edge": "Cosmos3Edge",
    "cosmos3_omni": "Cosmos3",
    "data2vec": "Data2Vec",
    "deepseek_vl": "DeepseekVL",
    "deepseek_vl_hybrid": "DeepseekVLHybrid",
    "deplot": "DePlot",
    "diffusion_gemma": "DiffusionGemma",
    "donut": "Donut",
    "edgetam": "EdgeTAM",
    "edgetam_video": "EdgeTAMVideo",
    "emu3": "Emu3",
    "ernie4_5_vl_moe": "Ernie45VLMoE",
    "evolla": "Evolla",
    "fast_vlm": "FastVLM",
    "flava": "FLAVA",
    "florence2": "Florence2",
    "gemma4_assistant": "Gemma4Assistant",
    "gemma4_unified_assistant": "Gemma4UnifiedAssistant",
    "gemma3": "Gemma3",
    "gemma3n": "Gemma3N",
    "gemma4": "Gemma4",
    "gemma4_unified": "Gemma4Unified",
    "git": "GIT",
    "glm46v": "GLM46V",
    "glm4v": "GLM4V",
    "glm4v_moe": "GLM4VMoe",
    "glmga": "GLMga",
    "glm_ocr": "GLMOCR",
    "got_ocr2": "GotOcr2",
    "granite4_vision": "Granite4Vision",
    "granitevision": "Granitevision",
    "grounding-dino": "GroundingDINO",
    "groupvit": "GroupViT",
    "idefics": "IDEFICS",
    "idefics2": "Idefics2",
    "idefics3": "Idefics3",
    "inkling": "Inkling",
    "instructblip": "InstructBLIP",
    "instructblipvideo": "InstructBLIPVideo",
    "internvl": "InternVL",
    "janus": "Janus",
    "kimi_k25": "KimiK25",
    "kosmos-2": "KOSMOS2",
    "kosmos2_5": "KOSMOS25",
    "layoutlm": "LayoutLM",
    "layoutlmv2": "LayoutLMV2",
    "layoutlmv3": "LayoutLMV3",
    "layoutxlm": "LayoutXLM",
    "lfm2_vl": "LFM2VL",
    "lighton_ocr": "LightOnOcr",
    "lilt": "LiLT",
    "llama4": "Llama4",
    "llava": "LLaVA",
    "llava_next": "LLaVANext",
    "llava_next_video": "LLaZVANextVideo",
    "llava_onevision": "LLaVAOneVision",
    "lxmert": "LXMERT",
    "matcha": "MatCha",
    "metaclip_2": "MetaCLIP2",
    "mgp-str": "MGPSTR",
    "minicpmv4_6": "MiniCPMV",
    "minicpmv": "MiniCPMV",
    "mistral3": "Mistral3",
    "mistral4": "Mistral4",
    "mllama": "Mllama",
    "mm-grounding-dino": "MMGroundingDINO",
    "musicflamingo": "MusicFlamingo",
    "nougat": "Nougat",
    "omdet-turbo": "OmDetTurbo",
    "oneformer": "OneFormer",
    "ovis2": "Ovis2",
    "owlvit": "OWLViT",
    "owlv2": "OWLv2",
    "paddleocr_vl": "PaddleOCRVL",
    "paligemma": "PaliGemma",
    "pe_audio_video": "PEAudioVideo",
    "perceiver": "Perceiver",
    "perception_lm": "PerceptionLM",
    "phi4_multimodal": "Phi4Multimodal",
    "phi4mm": "Phi4Multimodal",
    "pi0": "PI0",
    "pix2struct": "Pix2Struct",
    "pixtral": "Pixtral",
    "pp_doclayout_v2": "PPDocLayoutV2",
    "pp_doclayout_v3": "PPDocLayoutV3",
    "pp_formulanet": "PPFormulaNet",
    "pp_ocrv5_mobile_det": "PPOCRv5MobileDet",
    "pp_ocrv5_mobile_rec": "PPOCRv5MobileRec",
    "pp_ocrv5_server_det": "PPOCRv5ServerDet",
    "pp_ocrv5_server_rec": "PPOCRv5ServerRec",
    "pp_ocrv6_medium_det": "PPOCRv6MediumDet",
    "pp_ocrv6_small_det": "PPOCRv6SmallDet",
    "pp_ocrv6_small_rec": "PPOCRv6SmallRec",
    "pp_ocrv6_tiny_rec": "PPOCRv6TinyRec",
    "pp_chart2table": "PPChart2Table",
    "pp_lcnet": "PPLCNet",
    "pp_lcnet_v3": "PPLCNetV3",
    "pp_lcnet_v4": "PPLCNetV4",
    "qianfan_ocr": "QianfanOCR",
    "qwen2_5_omni": "Qwen25Omni",
    "qwen2_5_vl": "Qwen25VL",
    "qwen2_audio": "Qwen2Audio",
    "qwen2_vl": "Qwen2VL",
    "qwen3_omni_moe": "Qwen3OmniMoE",
    "qwen3_vl": "Qwen3VL",
    "qwen3_vl_moe": "Qwen3VLMoE",
    "sam3": "SAM3",
    "sam3_video": "SAM3Video",
    "sam3_lite_text": "SAM3LiteText",
    "shieldgemma2": "ShieldGemma2",
    "siglip": "SigLIP",
    "siglip2": "SigLIP2",
    "slanet": "SLANet",
    "slanext": "SLANeXt",
    "smolvlm": "SmolVLM",
    "speech-encoder-decoder": "SpeechEncoderDecoder",
    "tapas": "TAPAS",
    "tipsv2": "TIPSv2",
    "tipsv2_dpt": "TIPSv2DPT",
    "trocr": "TrOCR",
    "tvp": "TVP",
    "udop": "UDOP",
    "video_llama_3": "VideoLLaMA3",
    "video_llava": "VideoLLaVa",
    "vilt": "ViLT",
    "vipllava": "VipLlava",
    "vision-encoder-decoder": "VisionEncoderDecoder",
    "vision-text-dual-encoder": "VisionTextDualEncoder",
    "visual_bert": "VisualBERT",
    "voxtral": "Voxtral",
    "voxtral_realtime": "VoxtralRealtime",
    "xclip": "XCLIP",
    "decision_transformer": "DecisionTransformer",
    "autoformer": "Autoformer",
    "informer": "Informer",
    "patchtsmixer": "PatchTSMixer",
    "patchtst": "PatchTST",
    "time_series_transformer": "TimeSeriesTransformer",
    "timesfm": "TimesFM",
    "timesfm2_5": "TimesFM25",
}

from .canonical_kaggle import (ARCHITECTURE_CANONICAL, MODALITY_KAGGLE_CANONICAL, AUDIENCE_CANONICAL, LIBRARY_KAGGLE_CANONICAL, SUBJECT_CANONICAL, TASK_KAGGLE_CANONICAL, TECHNIQUE_CANONICAL, ANALYSIS_CANONICAL)   


CANONICALS = {
    "modality": MODALITY_CANONICAL,
    "format": FORMAT_CANONICAL,
    "size_category": SIZE_CATEGORY_CANONICAL,
    "dataset_library": DATASET_LIBRARY_CANONICAL,
    "model_library": MODEL_LIBRARY_CANONICAL,
    "task": TASK_CANONICAL,
    "subtask": SUBTASK_CANONICAL,
    "multilinguality": MULTILINGUARITY_CANONICAL,
    "model_family": MODEL_FAMILY_CANONICAL,

    "architecture": ARCHITECTURE_CANONICAL,
    "kaggle_modality": MODALITY_KAGGLE_CANONICAL,
    "audience": AUDIENCE_CANONICAL,
    "library": LIBRARY_KAGGLE_CANONICAL,
    "subject": SUBJECT_CANONICAL,    
    "kaggle_task": TASK_KAGGLE_CANONICAL,
    "technique": TECHNIQUE_CANONICAL,
    "analysis": ANALYSIS_CANONICAL,
}


def _canonical_lookup(value: str, canonical: str) -> str | None:
    mapping = CANONICALS.get(canonical, {})

    token = normalize_string(value)
    if not token:
        return None

    compact = re.sub(r"[-_\s]", "", token.lower())
    direct = mapping.get(token.lower()) or mapping.get(token) or mapping.get(compact)
    if direct:
        return direct

    camel_hyphen = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "-", token)
    camel_hyphen = re.sub(r"([0-9])-(?=[A-Za-z])", r"\1", camel_hyphen)
    camel_key = camel_hyphen.replace("_", "-").lower()
    return mapping.get(camel_key) or mapping.get(re.sub(r"[-_\s]", "", camel_key))

def pascal_case(value: str) -> str:
    """Generate PascalCase Turtle local names."""

    value = value.replace("_", " ").replace("-", " ")
    value = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", value)
    value = re.sub(r"(?<=[A-Za-z])(?=[0-9])", " ", value)
    value = re.sub(r"(?<=[0-9])(?=[A-Za-z])", " ", value)

    words = re.findall(r"[A-Za-z0-9]+", value)
    if not words:
        return "Item"

    return "".join(word[:1].upper() + word[1:] for word in words)

def canonicalize(values: list[str], canonical: str | None = None, fallback: bool = False) -> list[str]:
    output: list[str] = []
    values = values or []
    for value in values:
        canonical_localname = _canonical_lookup(value, canonical)

        if canonical_localname:
            output.append(canonical_localname)
            continue

        if fallback and value:
            output.append(pascal_case(value))
        else:
            output.append(value)

    return dedupe(output)

def get_canonical_tag_alone(tags: list[str], canonical: str) -> list[str]:
    values: list[str] = []
    mapping = CANONICALS.get(canonical, {})
    if not mapping:
        return []

    known_keys = set(mapping.keys())
    compact_keys = {re.sub(r"[-_\s]", "", key.lower()) for key in known_keys}

    for tag in tags:
        token = normalize_string(tag)
        if not token or ":" in token:
            continue

        normalized = token.lower()
        compact = re.sub(r"[-_\s]", "", normalized)

        if normalized in known_keys or compact in compact_keys:
            values.append(token)
            tags.remove(tag)
            continue

        if _canonical_lookup(token, canonical):
            values.append(token)
            tags.remove(tag)

    return dedupe(values)

def fallback_model_libraries(values: list[str]) -> tuple[list[str], list[dict[str, Any]]]:
    thesaurus_libraries: list[str] = []
    fallback_instances: list[dict[str, Any]] = []
    seen_fallback_hashes: set[str] = set()
    mapping = CANONICALS.get("model_library", {})
    if not mapping:
        return []

    known_keys = set(mapping.keys())
    
    if not isinstance(values, list):
        return [], []
    
    for value in values:
        token = normalize_string(value)
        if not token:
            continue

        normalized = token.lower()
        if normalized in known_keys:
            thesaurus_libraries.append(normalized)
            continue

        library_hash = hash16(normalized)
        if not library_hash or library_hash in seen_fallback_hashes:
            continue

        seen_fallback_hashes.add(library_hash)
        fallback_instances.append(
            {
                "library_hash16": library_hash,
                "library_label": token,
            }
        )

    return dedupe(thesaurus_libraries), fallback_instances