version: "3"
services:
  corese:
    image: wimmics/corese
    build: ./corese
    platform: linux/amd64
    container_name: corese-datalens
    ports:
      - "8050:8080"
    volumes:
      - ./corese-data:/usr/local/corese/data
      - ./config:/usr/local/corese/config
      - ./log:/usr/local/corese/log