PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX dlt: <http://ns.inria.fr/datalens/thesaurus/>
PREFIX dlo: <http://ns.inria.fr/datalens/ontology/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX cc: <http://creativecommons.org/licenses/>
PREFIX spdx: <https://spdx.org/licenses/>

SELECT * WHERE {
    # Filters
    ?datasetURI a dlo:Dataset ;
    	dlo:hasTask dlt:QuestionAnswering ;
    	dlo:hasModality dlt:Audio ;
    	dc:license ?license .
    
    # Descriptive information
    ?datasetURI	dc:identifier ?datasetName ;
    	dc:description ?description ;
    	dcat:landingPage ?sourceUrl .

    bind (REPLACE(
  REPLACE(
    STR(?license),
    STR(spdx:),
    ""
  ),
  STR(cc:),
  ""
) as ?licenseName)
}
