PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dlo: <http://[namespace]/datalens/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT * WHERE {
    ?resource dlo:downloadCount ?downloads ;
    dlo:likesCount ?likes .

    ?resource dcat:landingPage ?url ;
      dlo:hasModality [ skos:prefLabel ?modality ] ;
    	a ?type .
    
    ?type rdfs:subClassOf dlo:Ressource ; rdfs:label ?resourceType .

    FILTER (?downloads > 100 && ?likes < 9000)
}
