PREFIX mluo: <http://example.org/mluo/ontology#>
PREFIX mluo_th: <http://example.org/mluo/thesaurus#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dct: <http://purl.org/dc/terms/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX dcat: <http://www.w3.org/ns/dcat#> 
PREFIX bibo: <http://purl.org/ontology/bibo/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT distinct ?value (COUNT(?dataset) AS ?count) WHERE {
    ?task a mluo:Task ;
        rdfs:label ?value .

    ?dataset mluo:hasUsage [ mluo:hasTask ?task ] .
    
} GROUP BY ?value
ORDER BY DESC(?count)
