PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dlt: <http://ns.inria.fr/datalens/thesaurus/>
PREFIX dlo: <http://ns.inria.fr/datalens/ontology/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT *
WHERE {
    ?resource dlo:hasTask $task ;
    	dcterms:identifier ?resourceName ;
    	dlo:downloadCount ?downloads .
           
    VALUES ?p { dlo:hasLibrary
        dlo:hasAcademicArticle
        dcterms:license
        dlo:hasTask
        dlo:hasSubTask
        dlo:hasModality
        prov:wasDerivedFrom
        dlo:wasTrainedOn }

    ?resource ?p ?relation .
    { ?relation rdfs:label ?relationName }
    UNION
    { ?relation skos:prefLabel ?relationName }
    UNION
    { ?relation dcterms:identifier ?relationName }
    
    ?p rdfs:label ?pLabel .
    FILTER(LANGMATCHES(LANG(?pLabel), "en"))
    
    FILTER (?downloads > 10000)
}